image: node:16

stages:
  - build
  - test
  - publish

build:
  stage: build
  artifacts:
    paths:
      - lib
  cache:
    key:
      files:
        - yarn.lock
    policy: pull-push
    paths:
      - node_modules
  script:
    - yarn
    - yarn build

test:
  stage: test
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  cache:
    key:
      files:
        - yarn.lock
    policy: pull
    paths:
      - node_modules
  script:
    - yarn test

publish:
  stage: publish
  script:
    - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    - npm version --no-git-tag-version $CI_COMMIT_TAG --allow-same-version
    - npm publish --access=public
  only:
    - tags

pages:
  image: alpine
  stage: publish
  cache:
    key:
      files:
        - yarn.lock
    policy: pull
    paths:
      - node_modules
  script:
    - yarn docs
  artifacts:
    paths:
      - public
  only:
    - tags